name: Angular CI CD

on:
  push: 
    branches: [main]

jobs:
  angular:
    name: build and deploy
    runs-on: ubuntu-latest
    env:
      TOKEN_GIT: ${{ secrets.TOKEN }}
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: push build to diff branch
        run: |
          git config --global user.email pathakmayank021@gmail.com
          git config --global user.name dStrange6
          git checkout --orphan build-branch
          git reset --hard
          cp -r dist/* .
          git add .
          git commit -m "adding builds"
          git remote set-url origin https://${{ secrets.TOKEN }}@github.com/dStrange6/AngularApp.git
          git push origin build-branch
  
  

